# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Clean up state from a previous failed installer run

dontChroot: true
timeout: 10

script:
    - command: "userdel -r ${USER} 2>/dev/null || true"
      timeout: 10
